[profile.default]
src = "contracts/src"
out = "contracts/out"
test = "contracts/test"
libs = ["contracts/lib"]
solc_version = '0.8.33'
extra_output = ["storageLayout"]

[lint]
exclude_lints = ["mixed-case-function"]
ignore = [
  "contracts/lib/**",
]

[profile.default.fuzz]
corpus_dir = "corpus"
fail_on_revert = true

[invariant]
corpus_dir = "corpus"
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
